@base_address = http://localhost:3000/api/people

POST {{base_address}}
Content-Type: application/json

{
    
  "FirstName": "J",
  "LastName": "D"
}

###
GET {{base_address}}

###
GET {{base_address}}/1


###
PUT {{base_address}}/6
Content-Type: application/json

{
  "PersonId": 6,
  "FirstName": "Vinudiii",
  "LastName": "Shivudaaaa"
}

###
DELETE  {{base_address}}/4
