
using System.ComponentModel.DataAnnotations;

namespace Backend.Models;

public class Person
{
    public int PersonId { get; set; } //values generated by the database
    
    [Required]
    [MaxLength(30)]

    public string FirstName { get; set; } = string.Empty;

    [Required]
    [MaxLength(30)]
    public string LastName { get; set; } = string.Empty;
}